package Servlets;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class Analysis extends HttpServlet {

	protected void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		
		HashADU.getAdu().put("ALL_PRODUCTS","0");
		HashADU.getAdu().put("Xbox1","400");
		HashADU.getAdu().put("Xbox360","450");
		HashADU.getAdu().put("PS3","500");
		HashADU.getAdu().put("PS4","550");
		HashADU.getAdu().put("Wii","449.99");
		HashADU.getAdu().put("WiiU","559.99");
		
		PrintWriter pw = resp.getWriter();
		pw.println("<html><head><link rel='stylesheet' type='text/css' href='StyleSheet.css'><title>Data Analytics</title></head>"
				+ "<body><header>"
				+ "<h1><font face='Cambria'>GAMESPEED</font></h1></header>"
				+ "<nav><ul>"
				+ "<li><a href='Home.html' class='home'><font face='Cambria'>HOME</font></a></li>"
				+ "<li><a href='Microsoft.html' class='microsoft'><font face='Cambria'>MICROSOFT</font></a></li>"
				+ "<li><a href='Sony.html' class='sony'><font face='Cambria'>SONY</font></a></li>"
				+ "<li><a href='Nintendo.html' class='nintendo'><font face='Cambria'>NINTENDO</font></a></li>"
				+ "<li><a href='Tablet.html' class='tablet'><font face='Cambria'>TABLETS</font></a></li>"
				+ "</ul>"
				+ "<a href='Index.html'>SIGN OUT</a> <a href='vieworder'>CART</a>"
				+ "</nav>"
				+ "<div id='contain'>"
				+ "<section id='desc'>"
				+ "<form method='post' action='fdata'>"
				+ "<table class='query-table'>"
				+ "<tr><th colspan='4'><b> Simple Search </b></th></tr>"
				//
				+ "<tr><td><input type='checkbox' name='queryCheckBox'value='productName' checked> Select</td>"
				+ "<td>Product Name:</td>"
				+ "<td><select name='productName'>"
				+ "	<option value='ALL_PRODUCTS'>All Products</option>"
				+ "	<option value='Xbox1'>XBOX ONE</option>"
				+ "	<option value='Xbox360'>XBOX 360</option>"
				+ "	<option value='PS3'>PS 3</option>"
				+ "	<option value='PS4'>PS 4</option>"
				+ "	<option value='Wii'>WII</option>"
				+ "	<option value='WiiU'>WII-U</option>"
				+ "</select></td><td></td></tr>"
				+ "<tr><td><input type='checkbox' name='queryCheckBox'"
				+ "value='productCategory'> Select</td>"
				+ "<td>Product Category:</td>"
				+ "<td><select name='productCategory'>"
				+ "	<option value='All_C'>All</option>"
				+ "	<option value='Gaming Console'>Gaming Console</option>"
				+ "	<option value='Game'>Game</option>"
				+ "<option value='Accessories'>Accessories</option>"
				+ "<option value='Tablets'>Tablet</option>"
				+ "</select></td>"
				+ "<td></td>"
				+ "</tr>"
				+ "<tr><td><input type='checkbox' name='queryCheckBox'"
				+ "value='productPrice'> Select</td>"
				+ "<td>Product Price:</td>"
				+ "<td><input type='number' name='productPrice' value='0' size=10 /></td>"
				+ "<td><input type='radio' name='comparePrice' value='EQUALS_TO'"
				+ "checked> Equals <br> <input type='radio'"
				+ "name='comparePrice' value='GREATER_THAN'> Greater Than <br>"
				+ "<input type='radio' name='comparePrice' value='LESS_THAN'>"
				+ "Less Than</td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td><input type='checkbox' name='queryCheckBox'"
				+ "value='retailerName'> Select</td>"
				+ "<td>Retailer:</td>"
				+ "<td><input type='text' name='retailerName'></td>"
				+ "<td></td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td><input type='checkbox' name='queryCheckBox'"
				+ "value='retailerZipcode'> Select</td>"
				+ "<td>Retailer Zip code:</td>"
				+ "<td><input type='number' name='retailerZipcode'"
				+ "size=10 /></td>"
				+ "<td></td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td><input type='checkbox' name='queryCheckBox'"
				+ "value='retailerCity'> Select</td>"
				+ "<td>Retailer City:</td>"
				+ "<td><input type='text' name='retailerCity' value='All'/></td>"
				+ "<td></td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td><input type='checkbox' name='queryCheckBox'"
				+ "value='retailerState'> Select</td>"
				+ "<td>Retailer State:</td>"
				+ "<td><input type='text' name='retailerState' /></td>"
				+ "<td></td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td><input type='checkbox' name='queryCheckBox' value='pos'>"
				+ "Select</td>"
				+ "<td>Product On Sale:</td>"
				+ "<td><input type='radio' name='pos' value='Yes'>Yes"
				+ "<input type='radio' name='pos' value='No'>No</td>"
				+ "<td></td>"
				+ "</tr>"
				//
				+ "<tr>"
				+ "<td><input type='checkbox' name='queryCheckBox' value='mname'>"
				+ "Select</td>"
				+ "<td>Manufacturer Name:</td>"
				+ "<td><select name='mname'>"
				+ "<option value='Microsoft'>Microsoft</option>"
				+ "<option value='Sony'>Sony</option>"
				+ "<option value='Nintendo'>Nintendo</option>"
				+ "<option value='Electronic Arts'>Electronic Arts</option>"
				+ "<option value='Activision'>Activision</option>"
				+ "<option value='Take-Two Interactive'>Take-Two"
				+ "Interactive</option>"
				+ "</select></td>"
				+ "<td></td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td><input type='checkbox' name='queryCheckBox' value='mrebate'>"
				+ "Select</td>"
				+ "<td>Manufacturer Rebate:</td>"
				+ "<td><input type='radio' name='mrebate' value='Yes'>Yes"
				+ "<input type='radio' name='mrebate' value='No'>No</td>"
				+ "<td></td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td><input type='checkbox' name='queryCheckBox'"
				+ "value='userid'> Select</td>"
				+ "<td>User Id:</td>"
				+ "<td><input type='text' name='userid' /></td>"
				+ "<td></td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td><input type='checkbox' name='queryCheckBox'"
				+ "value='uage'> Select</td>"
				+ "<td>Age:</td>"
				+ "<td><input type='number' name='uage'"
				+ "size=10 /></td>"
				+ "<td><input type='radio' name='compareAge' value='EQUALS'"
				+ "checked> Equals <br> <input type='radio'"
				+ "name='compareAge' value='GREATER'> Greater Than <br>"
				+ "<input type='radio' name='compareAge' value='LESS'>"
				+ "Less Than</td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td><input type='checkbox' name='queryCheckBox' value='gender'>"
				+ "Select</td>"
				+ "<td>Gender:</td>"
				+ "<td><input type='radio' name='gender' value='Male'>Male"
				+ "<input type='radio' name='gender' value='Female'>Female</td>"
				+ "<td></td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td><input type='checkbox' name='queryCheckBox'"
				+ "value='occu'> Select</td>"
				+ "<td>Occupation:</td>"
				+ "<td><input type='text' name='occu' /></td>"
				+ "<td></td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td><input type='checkbox' name='queryCheckBox'"
				+ "value='reviewRating'> Select</td>"
				+ "<td>Review Rating:</td>"
				+ "<td><select name='reviewRating'>"
				+ "<option value='1' selected>1</option>"
				+ "<option value='2'>2</option>"
				+ "<option value='3'>3</option>"
				+ "<option value='4'>4</option>"
				+ "<option value='5'>5</option>"
				+ "</select></td>"
				+ "<td><input type='radio' name='compareRating'"
				+ "value='EQUALS_TO' checked> Equals <br>"
				+ "<input type='radio' name='compareRating' value='GREATER_THAN'>"
				+ "Greater Than</td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td><input type='checkbox' name='queryCheckBox' value='rdate'>"
				+ "Select</td>"
				+ "<td>Date:</td>"
				+ "<td><input type='date' name='rdate' /></td>"
				+ "<td></td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td>Return:</td>"
				+ "<td colspan='4'><select name='returnValue'>"
				+ "<option value='ALL' selected>All</option>"
				+ "<option value='TOP_5'>Top 5</option>"
				+ "<option value='TOP_10'>Top 10</option>"
				+ "<option value='LATEST_5'>Latest 5</option>"
				+ "<option value='LATEST_10'>Latest 10</option>"
				+ "</select></td>"
				+ "</tr>"
				+ "<tr><th colspan='4'><b> Grouping </b></th></tr>"
				+ "<tr><td><input type='checkbox' name='extraSettings'value='GROUP_BY'> "
				+ "Group By</td><td colspan='3'>"
				+ "<select name='groupByDropdown'>"
				+ "<option value='retailerCity' selected>City</option>"
				+ "<option value='productName'>Product Name</option>"
				+ "<option value='productCategory'>Product Category</option>"
				+ "<option value='productPrice'>Product Price</option>"
				+ "<option value='retailerName'>Retailer</option>"
				+ "<option value='retailerZipcode'>Zip Code</option>"
				+ "<option value='retailerState'>State</option>"
				+ "<option value='productOnSale'>Product On Sale</option>"
				+ "<option value='consoleManufacturer'>Manufacturer Name</option>"
				+ "<option value='manufacturerRebate'>Manufacturer Rebate</option>"
				+ "<option value='userID'>User Id</option>"
				+ "<option value='userAge'>Age</option>"
				+ "<option value='userGender'>Gender</option>"
				+ "<option value='userOccupation'>Occupation</option>"
				+ "<option value='reviewRating'>Rating</option>"
				+ "<option value='reviewDate'>Date</option>"
				+ "</select></td></tr>"

				+ "<tr><td><input type='checkbox' name='extraSettings' value='HIGH_PRICE'> "
				+ "Highest Price</td><td colspan='3'>"
				+ "<select name='highpriceDropdown'>"
				+ "<option value='HIGH_BY_CITY' selected>City</option>"
				+ "<option value='HIGH_BY_ZIP'>Zip Code</option>"
				+ "</select></td></tr>"

				+ "<tr><td><input type='checkbox' name='extraSettings' value='TOP_LIKED'> "
				+ "Top 5 Liked</td><td colspan='3'>"
				+ "<select name='top5Dropdown'>"
				+ "<option value='TOP5_BY_CITY' selected>City</option>"
				+ "</select></td></tr>"

				+ "<tr><td><input type='checkbox' name='extraSettings' value='TOP_RATED'> "
				+ "Rating 5</td><td colspan='3'>"
				+ "<select name='rating5Dropdown'>"
				+ "<option value='RATING5_BY_CITY' selected>City</option>"
				+ "</select></td></tr>"

				+ "<tr><td><input type='checkbox' name='extraSettings' value='MEDIAN'> "
				+ "Median</td><td colspan='3'>"
				+ "<select name='medianDropdown'>"
				+ "<option value='MEDIAN_BY_CITY' selected>City</option>"
				+ "</select></td></tr>"

				+ "<tr><td><input type='checkbox' name='extraSettings' value='ADVANCED'> "
				+ "Advanced Search</td><td colspan='3'>"
				+ "<input type='text' name='advances'>"
				+ "</td></tr>"

				+ "<tr><td colspan='2'><input type='submit' name='find' value='Find Data'/></td>"
				+ "<td colspan='2'><input type='submit' name='trending' value='Trending'/></td>"
				+ "</tr></table></form></section>"
				+ "<aside class='vnav'>"
				+ "<ul><li>"
				+ "<h3>Game Makers</h3>"
				+ "<ul><li><a href='EA.html'>Electronic Arts</a></li>"
				+ "<li><a href='Activision.html'>Activision</a></li>"
				+ "<li><a href='TTI.html'>Take-Two Interactive</a></li>"
				+ "</ul>"
				+ "<li><h3>Products</h3><ul>"
				+ "<li><a href='X1.html'>Xbox One</a></li>"
				+ "<li><a href='X360.html'>Xbox 360</a></li>"
				+ "<li><a href='Ps3.html'>PS3</a></li>"
				+ "<li><a href='Ps4.html'>PS4</a></li>"
				+ "<li><a href='Wii.html'>Wii</a></li>"
				+ "<li><a href='WiiU.html'>WiiU</a></li>"
				+ "</ul>"
				+ "</li>"
				+ "<li><h3>Accessories</h3><ul>"
				+ "<li><a href='Xc.html'>Xbox</a></li>"
				+ "<li><a href='Psc.html'>Play Station</a></li>"
				+ "<li><a href='Wiic.html'>Wii</a></li>"
				+ "</ul>"
				+ "</li>"
				+ "<li><h3>Data Analytics</h3><ul>"
				+ "<li><a href='analysis'>Data Analytics</a></li>"
				+ "</ul></li>"
				+ "</ul></aside>"
				+ "<div class='clear'></div>"
				+ "<div class='foo'> <p>Copyright © www.gamespeed.co.in</p> </div></div></body></html>");

	}
}
